language: python
cache:
  directories:
    - eggs
    - downloads
python: 2.7
install:
  - python bootstrap.py
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout buildout:download-cache=downloads
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls==0.5
  - coveralls
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.org#imio"
    on_success: change
    on_failure: always
